# Generated by Django 4.1.4 on 2024-04-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='app_user',
            new_name='user',
        ),
    ]
