# Generated by Django 4.1.4 on 2024-05-24 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='gender',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
