# Generated by Django 4.1.4 on 2024-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pricing_delete_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='date_of_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
